//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPets.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BaikeActivity
    {
        public int ActivedId { get; set; }
        [Display(Name ="广告标题")]
        public string ActivedTitle { get; set; }
        [Display(Name = "广告描述")]
        public string ActivedContent { get; set; }
        public string ActivedImg { get; set; }
        public string ActicedDetail { get; set; }
    }
}
