//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPets.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaikeQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaikeQuestion()
        {
            this.BaikeAnswer = new HashSet<BaikeAnswer>();
        }
    
        public int QuestionId { get; set; }
        public string QuestionTitle { get; set; }
        public string QuestionType { get; set; }
        public string QuestionDescribe { get; set; }
        public Nullable<System.DateTime> QuestionTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> isChoiceness { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaikeAnswer> BaikeAnswer { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
