//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPets.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baike
    {
        public int BaikeId { get; set; }
        public string BaikeSeries { get; set; }
        public string BaikeType { get; set; }
        public string BaikeTitle { get; set; }
        public string BaikeImg { get; set; }
        public string BaikeDescribe { get; set; }
        public string BaikeContent { get; set; }
        public System.DateTime BaikeTime { get; set; }
    }
}
