//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPets.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaikeAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaikeAnswer()
        {
            this.ResponAnswer = new HashSet<ResponAnswer>();
        }
    
        public int AnswerId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string AnswerContent { get; set; }
        public Nullable<System.DateTime> AnswerTime { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ClickNum { get; set; }
    
        public virtual BaikeQuestion BaikeQuestion { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponAnswer> ResponAnswer { get; set; }
    }
}
