//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPets.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsResponseComment
    {
        public int AnswerId { get; set; }
        public int CommentId { get; set; }
        public string AnswerContent { get; set; }
        public string UserName { get; set; }
        public System.DateTime AnswerTime { get; set; }
    
        public virtual GoodsComment GoodsComment { get; set; }
    }
}
