//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPets.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsComment()
        {
            this.GoodsResponseComment = new HashSet<GoodsResponseComment>();
        }
    
        public int CommentId { get; set; }
        public string CommentContent { get; set; }
        public string ContentRange { get; set; }
        public System.DateTime CommentTime { get; set; }
        public int GoodsId { get; set; }
        public int UsersId { get; set; }
        public bool IsReply { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsResponseComment> GoodsResponseComment { get; set; }
    }
}
