//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPets.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateMsg
    {
        public int PrivateMsgId { get; set; }
        public int SenderId { get; set; }
        public int ReceiverId { get; set; }
        public string PrivateMsgContent { get; set; }
        public string PrivateMsgEmail { get; set; }
        public string PrivateMsgTime { get; set; }
    }
}
