//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPets.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponAnswer
    {
        public int ResponseAnswerId { get; set; }
        public Nullable<int> AnswerId { get; set; }
        public string ResponContent { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> ResponTime { get; set; }
    
        public virtual BaikeAnswer BaikeAnswer { get; set; }
    }
}
