//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPets.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.BaikeAnswer = new HashSet<BaikeAnswer>();
            this.BaikeQuestion = new HashSet<BaikeQuestion>();
            this.Collect = new HashSet<Collect>();
            this.GoodsComment = new HashSet<GoodsComment>();
            this.Order = new HashSet<Order>();
            this.OrderDetail = new HashSet<OrderDetail>();
            this.Post = new HashSet<Post>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int UserId { get; set; }

        [Display(Name ="手机号")]
        public string UserPhone { get; set; }

        [Required(ErrorMessage = "邮箱不能为空")]
        [DataType(DataType.EmailAddress,ErrorMessage ="邮箱格式不正确")]
        public string UserEmail { get; set; }

        [Required(ErrorMessage ="用户名不能为空")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "密码不能为空")]
        [StringLength(100,MinimumLength =6,ErrorMessage ="密码长度不能少于6个字符")]
        [DataType(DataType.Password)]
        public string UserPwd { get; set; }

        [Required(ErrorMessage = "请确认密码")]
        [DataType(DataType.Password)]
        [Compare("UserPwd",ErrorMessage ="密码与确认密码不一致")]
        public string ConfirmPwd { get; set; }


        public string UserImg { get; set; }
        public bool IsSeller { get; set; }
        public string Range { get; set; }
        public Nullable<int> Score { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaikeAnswer> BaikeAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaikeQuestion> BaikeQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collect> Collect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsComment> GoodsComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
